name: CI - Build and Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t mydemoapp:latest .
        working-directory: ./MyDemoApp

      - name: Save Docker image as artifact
        run: docker save mydemoapp:latest -o mydemoapp.tar
      - name: Upload Docker image
        uses: actions/upload-artifact@v4
        with:
          name: mydemoapp-image
          path: mydemoapp.tar

  trivy-scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Docker image
        uses: actions/download-artifact@v4
        with:
          name: mydemoapp-image
          path: .

      - name: Load Docker image
        run: docker load -i mydemoapp.tar

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install wget -y
          wget https://github.com/aquasecurity/trivy/releases/download/v0.65.0/trivy_0.65.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.65.0_Linux-64bit.deb

      - name: Run Trivy scan on Docker image
        run: trivy image --severity CRITICAL --format table --exit-code 1 mydemoapp:latest | tee trivy-report.txt

      - name: Upload Trivy scan results
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.txt