name: Trivy Container Scan

on:
  workflow_run:
    workflows: ["Build Docker Image"]
    types: [completed]
    branches: [main]

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download Docker image
        uses: actions/download-artifact@v4
        with:
          name: mydemoapp-image
          path: .
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Load Docker image
        run: docker load -i mydemoapp.tar

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install wget -y
          wget https://github.com/aquasecurity/trivy/releases/download/v0.65.0/trivy_0.65.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.65.0_Linux-64bit.deb

      - name: Run Trivy scan on Docker image
        run: trivy image --severity CRITICAL --format table --exit-code 1 mydemoapp:latest | tee trivy-report.txt

      - name: Upload Trivy scan results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: trivy-report
          path: trivy-report.txt
          retention-days: 1